#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 23 19:36:40 PKT 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a487c6913c184d7dbb8b854c1927e984 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Sort_tb_behav xil_defaultlib.Sort_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto a487c6913c184d7dbb8b854c1927e984 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Sort_tb_behav xil_defaultlib.Sort_tb xil_defaultlib.glbl -log elaborate.log

